/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbankproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sthuthi
 */
public class Eligibility extends javax.swing.JFrame {

    /**
     * Creates new form Eligibility
     */
    public Eligibility() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        donid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InfecYes = new javax.swing.JRadioButton();
        InfecNo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        VirusYes = new javax.swing.JRadioButton();
        VirusNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        TDYes = new javax.swing.JRadioButton();
        TDNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        LastDonateDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        branchid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Donor ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));
        jPanel1.add(donid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Any Infection to the donor?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        InfecYes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        InfecYes.setText("Yes");
        InfecYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfecYesActionPerformed(evt);
            }
        });
        jPanel1.add(InfecYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, -1));

        InfecNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        InfecNo.setText("No");
        jPanel1.add(InfecNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 40, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Any Virus infection to the donor?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, -1));

        VirusYes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VirusYes.setText("Yes");
        VirusYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VirusYesActionPerformed(evt);
            }
        });
        jPanel1.add(VirusYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 50, -1));

        VirusNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VirusNo.setText("No");
        jPanel1.add(VirusNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 50, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Does the donor have any transmittable diseases?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 210, 300, -1));

        TDYes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TDYes.setText("Yes");
        jPanel1.add(TDYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 50, -1));

        TDNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TDNo.setText("No");
        TDNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TDNoActionPerformed(evt);
            }
        });
        jPanel1.add(TDNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 40, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Last Donated Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 30));
        jPanel1.add(LastDonateDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, 30));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 80, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Branch ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, -1));
        jPanel1.add(branchid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 110, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Eligibility Check Form");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 240, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sthuthi\\Downloads\\preview (1).jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 650, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(623, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InfecYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfecYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfecYesActionPerformed

    private void VirusYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VirusYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VirusYesActionPerformed

    private void TDNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TDNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TDNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank", "root", "root123");
            String sql="insert into donates values(?,?,?,?,?,?)";
            PreparedStatement pstm=con.prepareStatement(sql);
            String sql1="delete from donor where donid=?";
            PreparedStatement pstm1=con.prepareStatement(sql1);
            pstm1.setString(1,donid.getText());
            pstm.setString(1, donid.getText());
            pstm.setString(2, branchid.getText());
            String dod;
            dod=""+LastDonateDate.getDate();
            Date dod1;
            dod1=LastDonateDate.getDate();
            int monthd=dod1.getMonth();
            System.out.println(monthd);
            pstm.setString(6,dod);
            System.out.println("date="+dod);
            /*int monthd=dod.getMonth();
            pstm.setString(6, (java.sql.Date) dod);*/
      
            Date d=new Date();
            int month = d.getMonth();
            
            System.out.println("month"+month);
            String infection=""; 
            String virus="";
            String TransmittableDisease="";
            if(InfecNo.isSelected())
            {
                infection=InfecNo.getText();
                if(VirusNo.isSelected())
                {
                    virus=VirusNo.getText();
                    if(TDNo.isSelected())
                    {
                        TransmittableDisease=TDNo.getText();
                        if(monthd-month<=8)
                    {
                        JOptionPane.showMessageDialog(null, "Eligible to donate");
                         new DonorForm().setVisible(true);
                        dispose();
                    }
                        else if(monthd-month>8)
                        {
                            JOptionPane.showMessageDialog(null, "Not eligible to donate");
                            pstm1.executeUpdate();
                            
                        } 
                    
                    }
                    else if(TDYes.isSelected())
                    {
                        TransmittableDisease=TDYes.getText();
                        JOptionPane.showMessageDialog(null, "Not eligible to donate");
                        pstm1.executeUpdate();
                    }
                    
                }
                else if(VirusYes.isSelected())
                    {
                        virus=VirusYes.getText();
                        JOptionPane.showMessageDialog(null, "Not eligible to donate");
                        pstm1.executeUpdate();
                    }
                
            }
            else if(InfecYes.isSelected())
                {
                        infection=InfecYes.getText();
                        JOptionPane.showMessageDialog(null, "Not eligible to donate");
                        pstm1.executeUpdate();
                }
            
            pstm.setString(3,infection);
            pstm.setString(4,virus);
            pstm.setString(5,TransmittableDisease);
  
            
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "New Donor details inserted!");
            con.close();
            
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eligibility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton InfecNo;
    private javax.swing.JRadioButton InfecYes;
    private com.toedter.calendar.JDateChooser LastDonateDate;
    private javax.swing.JRadioButton TDNo;
    private javax.swing.JRadioButton TDYes;
    private javax.swing.JRadioButton VirusNo;
    private javax.swing.JRadioButton VirusYes;
    private javax.swing.JTextField branchid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField donid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
