/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbankproj;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Sthuthi
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size= toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NewDon = new javax.swing.JButton();
        DonDet = new javax.swing.JButton();
        NewPat = new javax.swing.JButton();
        PatDet = new javax.swing.JButton();
        BranchDet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        HospDet = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Home");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 70, 50));

        NewDon.setBackground(new java.awt.Color(135, 210, 249));
        NewDon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NewDon.setText("New Donor");
        NewDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewDonActionPerformed(evt);
            }
        });
        getContentPane().add(NewDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        DonDet.setBackground(new java.awt.Color(135, 210, 249));
        DonDet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DonDet.setText("Donor Details");
        DonDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonDetActionPerformed(evt);
            }
        });
        getContentPane().add(DonDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, -1));

        NewPat.setBackground(new java.awt.Color(135, 210, 249));
        NewPat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NewPat.setText("New Patient");
        NewPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPatActionPerformed(evt);
            }
        });
        getContentPane().add(NewPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        PatDet.setBackground(new java.awt.Color(135, 210, 249));
        PatDet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PatDet.setText("Patient Details");
        PatDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatDetActionPerformed(evt);
            }
        });
        getContentPane().add(PatDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 120, -1));

        BranchDet.setBackground(new java.awt.Color(135, 210, 249));
        BranchDet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BranchDet.setText("Branch Details");
        BranchDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchDetActionPerformed(evt);
            }
        });
        getContentPane().add(BranchDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 130, 30));

        jButton1.setBackground(new java.awt.Color(135, 210, 249));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        HospDet.setBackground(new java.awt.Color(135, 210, 249));
        HospDet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HospDet.setText("Hospital Details");
        HospDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospDetActionPerformed(evt);
            }
        });
        getContentPane().add(HospDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 130, -1));

        jButton2.setBackground(new java.awt.Color(135, 210, 249));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Availability");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sthuthi\\Downloads\\images (22).jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewDonActionPerformed
        // TODO add your handling code here:
        new DonorForm().setVisible(true);
                dispose();
    }//GEN-LAST:event_NewDonActionPerformed

    private void DonDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonDetActionPerformed
        // TODO add your handling code here:
        new DonTable().setVisible(true);
                dispose();
    }//GEN-LAST:event_DonDetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NewPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPatActionPerformed
        // TODO add your handling code here:
        new PatientForm().setVisible(true);
            dispose();
    }//GEN-LAST:event_NewPatActionPerformed

    private void PatDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatDetActionPerformed
        // TODO add your handling code here:
        new PatTable().setVisible(true);
            dispose();
    }//GEN-LAST:event_PatDetActionPerformed

    private void BranchDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchDetActionPerformed
        // TODO add your handling code here:
        new BranchDet().setVisible(true);
            dispose();
    }//GEN-LAST:event_BranchDetActionPerformed

    private void HospDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospDetActionPerformed
        // TODO add your handling code here:
        new HospitalDet().setVisible(true);
            dispose();
    }//GEN-LAST:event_HospDetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Availability().setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BranchDet;
    private javax.swing.JButton DonDet;
    private javax.swing.JButton HospDet;
    private javax.swing.JButton NewDon;
    private javax.swing.JButton NewPat;
    private javax.swing.JButton PatDet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
